import type { AuditLogEntry, AutomodRuleInfo, BanInfo, StickerInfo } from '../../api/types';
import { EMPTY_AVATARS, EMPTY_BLUESKY_IDENTITIES, EMPTY_BOOKMARKS, EMPTY_BOT_TOKENS, EMPTY_CATEGORIES, EMPTY_CHANNELS_MAP, EMPTY_CHANNEL_OVERRIDES, EMPTY_COMMUNITY, EMPTY_DIRECT_CONVERSATIONS, EMPTY_DISCOVER, EMPTY_EMOJI, EMPTY_EVENTS, EMPTY_FORUM_TAGS, EMPTY_HAS_MORE, EMPTY_INVITES, EMPTY_MEMBERS_MAP, EMPTY_MEMBER_ROLES, EMPTY_MESSAGES_MAP, EMPTY_NOTIFICATION_SETTINGS, EMPTY_OAUTH2_APPS, EMPTY_PINS, EMPTY_PRESENCES, EMPTY_PROFILES, EMPTY_READ_SEQUENCES, EMPTY_ROLES, EMPTY_SERVERS, EMPTY_SLASH_COMMANDS, EMPTY_TEMPLATES, EMPTY_THREADS, EMPTY_TYPING, EMPTY_UNREAD, EMPTY_WEBHOOKS } from './defaults';
import type { ChatState } from './types';

export function createInitialState(): Pick<ChatState, 'connected' | 'operationGeneration' | 'syncCursor' | 'syncWindowCursors' | 'pendingCommands' | 'accountGeneration' | 'protectedGeneration' | 'durableMode' | 'ownPresenceStatus' | 'ownRequestedStatus' | 'ownCustomStatus' | 'ownStatusEmoji' | 'entityVersions' | 'readSequences' | 'drafts' | 'compositionFiles' | 'failedCompositions' | 'directConversations' | 'activeAccountId' | 'nickname' | 'servers' | 'channels' | 'messages' | 'members' | 'hasMore' | 'avatars' | 'typingUsers' | 'replyingTo' | 'unreadCounts' | 'customEmoji' | 'roles' | 'categories' | 'presences' | 'userProfiles' | 'searchResults' | 'searchQuery' | 'searchTotalCount' | 'searchOffset' | 'searchNextContinuation' | 'searchContinuationTokens' | 'activeSearchRequestId' | 'searchRestarted' | 'deletedMessageIds' | 'pinnedMessages' | 'threads' | 'forumTags' | 'bookmarks' | 'notificationSettings' | 'memberRoles' | 'roleProjectionVersions' | 'channelPermissionOverrides' | 'auditLog' | 'bans' | 'automodRules' | 'invites' | 'serverEvents' | 'eventRsvps' | 'communitySettings' | 'discoverableServers' | 'channelFollows' | 'templates' | 'webhooks' | 'slashCommands' | 'botTokens' | 'botAccounts' | 'botCredential' | 'oauth2Apps' | 'blueskyIdentities' | 'atprotoSyncEnabled' | 'stickers' | 'allUserEmoji' | 'serverAvatars' | 'maxMessageLength' | 'maxFileSizeMb' | 'errorToast' | 'ws'> {
  return {
    connected: false,
    operationGeneration: null,
    syncCursor: null,
    syncWindowCursors: {},
    pendingCommands: {},
    accountGeneration: 0,
    protectedGeneration: 0,
    durableMode: false,
    ownPresenceStatus: null,
    ownRequestedStatus: null,
    ownCustomStatus: null,
    ownStatusEmoji: null,
    entityVersions: {},
    readSequences: EMPTY_READ_SEQUENCES,
    drafts: {},
    compositionFiles: {},
    failedCompositions: [],
    directConversations: EMPTY_DIRECT_CONVERSATIONS,
    activeAccountId: null,
    nickname: null,
    servers: EMPTY_SERVERS,
    channels: EMPTY_CHANNELS_MAP,
    messages: EMPTY_MESSAGES_MAP,
    members: EMPTY_MEMBERS_MAP,
    hasMore: EMPTY_HAS_MORE,
    avatars: EMPTY_AVATARS,
    typingUsers: EMPTY_TYPING,
    replyingTo: null,
    unreadCounts: EMPTY_UNREAD,
    customEmoji: EMPTY_EMOJI,
    roles: EMPTY_ROLES,
    categories: EMPTY_CATEGORIES,
    presences: EMPTY_PRESENCES,
    userProfiles: EMPTY_PROFILES,
    searchResults: null,
    searchQuery: '',
    searchTotalCount: 0,
    searchOffset: 0,
    searchNextContinuation: null,
    searchContinuationTokens: {},
    activeSearchRequestId: null,
    searchRestarted: false,
    deletedMessageIds: {},
    pinnedMessages: EMPTY_PINS,
    threads: EMPTY_THREADS,
    forumTags: EMPTY_FORUM_TAGS,
    bookmarks: EMPTY_BOOKMARKS,
    notificationSettings: EMPTY_NOTIFICATION_SETTINGS,
    memberRoles: EMPTY_MEMBER_ROLES,
    roleProjectionVersions: {},
    channelPermissionOverrides: EMPTY_CHANNEL_OVERRIDES,
    auditLog: {} as Record<string, AuditLogEntry[]>,
    bans: {} as Record<string, BanInfo[]>,
    automodRules: {} as Record<string, AutomodRuleInfo[]>,
    invites: EMPTY_INVITES,
    serverEvents: EMPTY_EVENTS,
    eventRsvps: {},
    communitySettings: EMPTY_COMMUNITY,
    discoverableServers: EMPTY_DISCOVER,
    channelFollows: {},
    templates: EMPTY_TEMPLATES,
    webhooks: EMPTY_WEBHOOKS,
    slashCommands: EMPTY_SLASH_COMMANDS,
    botTokens: EMPTY_BOT_TOKENS,
    botAccounts: [],
    botCredential: null,
    oauth2Apps: EMPTY_OAUTH2_APPS,
    blueskyIdentities: EMPTY_BLUESKY_IDENTITIES,
    atprotoSyncEnabled: false,
    stickers: {} as Record<string, StickerInfo[]>,
    allUserEmoji: [],
    serverAvatars: {} as Record<string, Record<string, string>>,
    maxMessageLength: 4000,
    maxFileSizeMb: 100,
    errorToast: null,
    ws: null
  };
}
